#!/usr/bin/env python
"""One-command downstream orchestrator for a BioSeq grammar-LLaDA checkpoint.

Purpose
-------
Given a single trained checkpoint (e.g. the integrated
``grammar_v2_esmc300m_integrated_llada/best.pt``), build/run the *entire*
downstream comparison panel under the mandatory post-LLaDA ``global`` protocol
(see ``downstream/benchmark/PROJGUIDE.md``) and aggregate every task's metric
file into a single ``summary.json`` + Markdown table. This makes "iterate the
model -> compare against baselines" a one-liner:

    # print the exact per-task commands for a checkpoint (validate wiring)
    python scripts/downstream/run_all_downstream.py plan \
        --checkpoint output/grammar_v2_esmc300m_integrated_llada/best.pt

    # aggregate whatever metric files already exist for this run into a summary
    python scripts/downstream/run_all_downstream.py collect \
        --checkpoint output/grammar_v2_esmc300m_integrated_llada/best.pt \
        --out output/downstream_generation/summary_integrated.json

    # actually execute selected task families locally (heavy; prefer Volc YAMLs)
    python scripts/downstream/run_all_downstream.py run --only t3,flab \
        --checkpoint output/grammar_v2_esmc300m_integrated_llada/best.pt

Design
------
Heavy GPU work normally goes to Volc via ``eval_jobs/eval_integrated_*.yml``
(generated by ``scripts/downstream/gen_eval_integrated_ymls.sh``); this script
is the single source of truth for *what* each task runs and *where* its metrics
land, so ``plan`` and the YAML generator stay in sync. Ours features are always
``grammar:decoder:global:`` (post-LLaDA whole-record mean-pool); encoder-only /
segment specs are never emitted here.

Env: conda ``protenix_abtcr`` (as in the eval YAMLs).
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

ROOT = Path("/vepfs-mlp2/c20250601/251105016/project/dllm_test")
BENCH = ROOT / "downstream" / "benchmark"
BOUT = BENCH / "outputs"
GEN = ROOT / "output" / "downstream_generation"


def run_name_of(ckpt: Path) -> str:
    """``.../grammar_v2_esmc300m_integrated_llada/best.pt`` -> run dir name."""
    return ckpt.parent.name


def default_tag(ckpt: Path) -> str:
    """post-LLaDA global-pool tag, consistent with the eval YAMLs' ``ours_globalfeat_*``."""
    run = run_name_of(ckpt)
    short = run.replace("grammar_v2_", "").replace("_llada", "")
    return f"ours_globalfeat_{short}"


# --------------------------------------------------------------------------- #
# Task registry: each family declares the shell steps it runs and a collector
# that reads its metric file(s) into a flat dict for the summary.
# --------------------------------------------------------------------------- #
@dataclass
class Task:
    key: str
    title: str
    cwd: Path
    steps: Callable[["Ctx"], list[str]]
    collect: Callable[["Ctx"], dict[str, Any]]


@dataclass
class Ctx:
    ckpt: Path
    run: str
    tag: str  # post-LLaDA globalfeat tag for TCR tasks
    grammar_spec: str = field(init=False)  # grammar:decoder:global:<ckpt>
    mint_spec: str = field(init=False)  # grammar:<ckpt> (global pool default)
    nbbench_emb: str = field(init=False)  # grammar:decoder:<ckpt>
    flab_spec: str = field(init=False)  # bioseq-llada:<ckpt>
    ab_variant: str = field(init=False)

    def __post_init__(self) -> None:
        c = str(self.ckpt)
        self.grammar_spec = f"grammar:decoder:global:{c}"
        self.mint_spec = f"grammar:{c}"
        self.nbbench_emb = f"grammar:decoder:{c}"
        self.flab_spec = f"bioseq-llada:{c}"
        # AB CDR/pairing runner keys off the run-dir suffix after grammar_v2_
        self.ab_variant = self.run.replace("grammar_v2_", "")


def _read_json(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text())
    except Exception:
        return None


# ---- T1: TCR-epitope binding (NM2025) ------------------------------------- #
def t1_steps(c: Ctx) -> list[str]:
    return [
        f'python tcr_binding/run_nm2025.py --method embed --track cdr3b '
        f'--embedder "{c.grammar_spec}" --head mlp --tag "{c.tag}"',
        "python scripts/summarize_nm2025.py",
    ]


def t1_collect(c: Ctx) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for split in ("seen", "unseen"):
        m = _read_json(BOUT / "tcr_binding_nm2025" / c.tag / "cdr3b" / split / "metrics.json")
        if m:
            out[f"{split}_AUPRC"] = round(float(m.get("auprc_overall", float("nan"))), 4)
            out[f"{split}_AUROC"] = round(float(m.get("auroc_overall", float("nan"))), 4)
    return out


# ---- T2: TCR clustering (basis B: TCREmbedding ARI/NMI/Purity) ------------- #
def t2_steps(c: Ctx) -> list[str]:
    return [
        f'python tcr_clustering/run.py --method embed-threshold '
        f'--embedder "{c.grammar_spec}" --tag "{c.tag}"',
        f'python tcr_clustering/run_embed_bench.py --embedder "{c.grammar_spec}" '
        f'--tag "{c.tag}" --algos kmeans,hierarchical',
        "python scripts/summarize_tcrembedding_clustering.py",
    ]


def t2_collect(c: Ctx) -> dict[str, Any]:
    import csv

    f = BOUT / "tcr_clustering_embed" / "_summary.csv"
    if not f.is_file():
        return {}
    with f.open(newline="") as handle:
        for row in csv.DictReader(handle):
            if row.get("tag") == c.tag:
                return {
                    "ARI": round(float(row["kmeans_ari_mean"]), 4),
                    "NMI": round(float(row["kmeans_nmi_mean"]), 4),
                    "Purity": round(float(row["kmeans_purity_mean"]), 4),
                }
    return {}


# ---- T3: TCR representation (deep 6-pMHC few-shot) ------------------------- #
def t3_tag(c: Ctx) -> str:
    # T3 YAML appends _llada to the tag; keep parity so collect finds the dir.
    return c.tag if c.tag.endswith("_llada") else f"{c.tag}_llada"


def t3_steps(c: Ctx) -> list[str]:
    tag = t3_tag(c)
    return [
        f'python tcr_representation/run_paper6.py --method embed '
        f'--embedder "{c.grammar_spec}" --columns cdr3b cdr3a --tag "{tag}"',
        f'python tcr_representation/run.py --method embed '
        f'--embedder "{c.grammar_spec}" --columns cdr3b cdr3a --tag "{tag}"',
        "python scripts/summarize_tcr_representation_paper6.py",
    ]


def t3_collect(c: Ctx) -> dict[str, Any]:
    m = _read_json(BOUT / "tcr_representation_paper6" / t3_tag(c) / "fewshot.json")
    if not m:
        return {}
    by_shot = m.get("auroc_by_shot", {})
    out: dict[str, Any] = {}
    for k in ("5", "20", "100", "200"):
        v = by_shot.get(k) if isinstance(by_shot, dict) else None
        if isinstance(v, dict):  # {mean,std}
            v = v.get("mean")
        if v is not None:
            out[f"deep_k{k}"] = round(float(v), 4)
    return out


# ---- T4: TCR generation (Setting A/B) ------------------------------------- #
def t4_tag(c: Ctx) -> str:
    return f"ours_bioseq_{c.run.replace('grammar_v2_', '')}"


def t4_steps(c: Ctx) -> list[str]:
    tag = t4_tag(c)
    base = f"outputs/tcr_generation_bench"
    return [
        f"python scripts/run_bioseq_all.py --checkpoint {c.ckpt} "
        f"--tag {tag} --k 100 --n-uncond 5000 --n-full 500",
        f"python tcr_generation_bench/run.py --setting A --method file "
        f"--samples-file {base}/setting_A/{tag}/samples.txt --tag {tag} --n 5000",
        f"python tcr_generation_bench/run.py --setting B --method file "
        f"--samples-file {base}/setting_B/{tag}/designs.jsonl --tag {tag} -k 100",
        f"python scripts/score_bioseq_fulllength.py --tag {tag} "
        f"--samples-file {base}/setting_C/{tag}/full.jsonl",
        "python scripts/summarize_tcr_generation_bench.py",
    ]


def t4_collect(c: Ctx) -> dict[str, Any]:
    root = BOUT / "tcr_generation_bench"
    tag = t4_tag(c)
    out: dict[str, Any] = {}

    a = _read_json(root / "setting_A" / tag / "metrics.json")
    if a:
        metrics = a.get("metrics", a)
        for source, target in (
            ("kmer_jsd", "settingA_jsd"),
            ("novelty", "settingA_novelty"),
            ("mean_nn_distance", "settingA_mean_nn_distance"),
        ):
            if metrics.get(source) is not None:
                out[target] = round(float(metrics[source]), 4)
        pgen = metrics.get("pgen_generated", {})
        if isinstance(pgen, dict) and pgen.get("frac_pgen_positive") is not None:
            out["settingA_pgen_positive"] = round(float(pgen["frac_pgen_positive"]), 4)

    b = _read_json(root / "setting_B" / tag / "metrics.json")
    if b:
        summary = b.get("summary", {})
        for view in ("overall", "held20", "benchmark14", "bioseq_unseen"):
            row = summary.get(view, {}) if isinstance(summary, dict) else {}
            for metric in ("precision", "recall", "f1", "d_edit", "seq_recovery", "diversity"):
                if row.get(metric) is not None:
                    out[f"settingB_{view}_{metric}"] = round(float(row[metric]), 4)

    c_metrics = _read_json(root / "setting_C" / tag / "metrics.json")
    if c_metrics:
        validity = c_metrics.get("fulllength_validity", {})
        for source, target in (
            ("frac_valid_aa", "settingC_valid_aa"),
            ("frac_cdr3_extracted", "settingC_cdr3_extracted"),
        ):
            if validity.get(source) is not None:
                out[target] = round(float(validity[source]), 4)
        dist = c_metrics.get("cdr3b_distribution") or {}
        if dist.get("kmer_jsd") is not None:
            out["settingC_extracted_cdr3_jsd"] = round(float(dist["kmer_jsd"]), 4)
    return out


# ---- MINT GeneralPPI ------------------------------------------------------- #
MINT_TASKS = ("HumanPPI", "Bernett", "YeastPPI", "MutationalPPI", "SKEMPI")
MINT_DATA_PROTOCOL_ID = "mint_official_06694b7"


def _mint_cache(c: Ctx) -> str:
    return f"grammar_{c.run}_globalfeat_{MINT_DATA_PROTOCOL_ID}_t3000"


def mint_steps(c: Ctx) -> list[str]:
    cache = _mint_cache(c)
    steps: list[str] = []
    for task in MINT_TASKS:
        steps.append(
            f'python -m downstream.mint_tasks.extract_embeddings '
            f'--task "{task}" --model "{c.mint_spec}" --bs 4 --max_length 512 --max_train 3000'
        )
        steps.append(
            f'python -m downstream.mint_tasks.finetune_general '
            f'--task "{task}" --model "{c.mint_spec}" --rep 3 --max_train 3000  '
            f'# cache={cache}'
        )
    return steps


def mint_collect(c: Ctx) -> dict[str, Any]:
    cache = _mint_cache(c)
    out: dict[str, Any] = {}
    # MINT's five selected tasks do not share one metrics schema.  The three PPI
    # classification tasks use ``best_test_*`` keys, MutationalPPI uses plain
    # classification keys, and SKEMPI reports held-out splits explicitly. Keep
    # one canonical set of names in the aggregate summary.
    metric_aliases = (
        ("best_test_AUROC_mean", "AUROC"),
        ("best_test_AUPRC_mean", "AUPRC"),
        ("best_test_Accuracy_mean", "Accuracy"),
        ("best_test_F1 Score_mean", "F1"),
        ("best_test_Pearson_mean", "Pearson"),
        ("best_test_Spearman_mean", "Spearman"),
        ("best_test_RMSE_mean", "RMSE"),
        ("AUROC_mean", "AUROC"),
        ("AUPRC_mean", "AUPRC"),
        ("Accuracy_mean", "Accuracy"),
        ("F1 Score_mean", "F1"),
        ("pearson_split_2_mean", "Pearson"),
        ("spearman_split_2_mean", "Spearman"),
        ("rmse_split_2_mean", "RMSE"),
        ("pearson_mean", "Pearson"),
        ("spearman_mean", "Spearman"),
        ("rmse_mean", "RMSE"),
    )
    for task in MINT_TASKS:
        f = GEN / "mint_tasks" / task / cache / f"{task}_{cache}_metrics.json"
        m = _read_json(f)
        if not m:
            continue
        row = m[-1] if isinstance(m, list) and m else m
        for source, target in metric_aliases:
            if isinstance(row, dict) and row.get(source) is not None:
                out[f"{task}:{target}"] = round(float(row[source]), 4)
    return out


# ---- AB CDR infilling + light pairing ------------------------------------- #
def ab_steps(c: Ctx) -> list[str]:
    # Humanization is optional/expensive; skip unless RUN_HUMANIZATION=1.
    return [
        f"SKIP_HUMANIZATION=1 bash scripts/downstream/run_grammar_v2_variant_downstream_eval.sh "
        f"{c.ab_variant} {c.ckpt}",
    ]


def ab_collect(c: Ctx) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for cdr in ("cdrh1", "cdrh2", "cdrh3"):
        log = GEN / f"grammar_v2_{c.ab_variant}_{cdr}_10fold.log"
        if not log.is_file():
            continue
        for line in reversed(log.read_text().splitlines()):
            if line.startswith("Average AAR all folds:"):
                out[f"{cdr}_aar_all_folds"] = round(float(line.split(":", 1)[1]), 4)
                break
    pj = _read_json(GEN / f"grammar_v2_{c.ab_variant}_light_pairing_holdout500_prompt3_metrics.json")
    if pj:
        # A fully invalid generation can legitimately score exactly 0.0.  Do
        # not use truthiness here: ``0.0 or fallback`` turns that valid result
        # into None when the legacy key is absent.
        pairing_score = pj.get("gen_immunomatch_mean")
        if pairing_score is None:
            pairing_score = pj.get("gen_ImmunoMatch")
        out["pairing_gen_immunomatch"] = pairing_score
    return out


# ---- FLAb property regression --------------------------------------------- #
FLAB_DS = ("g6_Kd", "g6_er", "trastuzumab_kd", "d44_Kd")


def flab_out_stem(c: Ctx) -> str:
    # Keep per-run artifacts so successive ckpts do not overwrite each other.
    return f"grammar_{c.run.replace('grammar_v2_', '')}"


def flab_steps(c: Ctx) -> list[str]:
    stem = flab_out_stem(c)
    steps: list[str] = []
    for dtag, fname in (
        ("g6_Kd", "koenig2017mutational_kd_g6.csv"),
        ("g6_er", "koenig2017mutational_er_g6.csv"),
        ("trastuzumab_kd", "shanehsazzadeh2023unlocking_zerokd_trastuzumab.csv"),
        ("d44_Kd", "warszawski2019_d44_Kd.csv"),
    ):
        out = GEN / "flab_baselines" / f"{dtag}__{stem}.json"
        steps.append(
            f'FLAB_N_JOBS=8 OMP_NUM_THREADS=1 python scripts/downstream/run_flab_parallel.py '
            f'--dataset data/downstream/flab/flab_raw/{fname} '
            f'--embedder "{c.flab_spec}" --target-col fitness --output {out}'
        )
    return steps


def flab_collect(c: Ctx) -> dict[str, Any]:
    stem = flab_out_stem(c)
    out: dict[str, Any] = {}
    for dtag in FLAB_DS:
        m = _read_json(GEN / "flab_baselines" / f"{dtag}__{stem}.json")
        # Figure 3b's paper-aligned protocol uses the mean outer-fold R² from
        # nested 10x5 CV.  Pooled Spearman remains in the task artifact as a
        # diagnostic, but must not be promoted to the aggregate primary row.
        if m and m.get("r2_mean") is not None:
            out[f"{dtag}:R2"] = round(float(m["r2_mean"]), 4)
    return out


# ---- NbBench 12-task probing ---------------------------------------------- #
def nb_tag(c: Ctx) -> str:
    return f"ours_{c.run.replace('grammar_v2_', '')}"


def nb_steps(c: Ctx) -> list[str]:
    tag = nb_tag(c)
    return [
        f'python nbbench/run.py --task all --embedder "{c.nbbench_emb}" --tag {tag}',
        f'python nbbench/run_residue.py --task all --embedder "{c.nbbench_emb}" --tag {tag}',
        f"python nbbench/run_generative.py --checkpoint-path {c.ckpt} --tag {tag} "
        f"--max-iter 8 --sampling-strategy argmax --developability",
        "python scripts/summarize_nbbench.py",
    ]


def nb_collect(c: Ctx) -> dict[str, Any]:
    tag = nb_tag(c)
    root = BOUT / "nbbench"
    out: dict[str, Any] = {}

    for path in (
        root / f"_summary_{tag}.json",
        root / f"_summary_residue_{tag}.json",
    ):
        rows = _read_json(path)
        if not isinstance(rows, list):
            continue
        for row in rows:
            if not isinstance(row, dict) or row.get("primary") is None:
                continue
            task = str(row.get("task", "unknown"))
            metric = str(row.get("metric", "primary"))
            out[f"{task}:{metric}"] = round(float(row["primary"]), 4)

    gen = _read_json(root / "CDRInfilling" / f"gen_{tag}" / "metrics.json")
    if gen:
        for source, target in (
            ("br_masked", "CDRInfilling_gen:br_masked"),
            ("em_masked", "CDRInfilling_gen:em_masked"),
            ("exact_seq_rate", "CDRInfilling_gen:exact_seq_rate"),
        ):
            if gen.get(source) is not None:
                out[target] = round(float(gen[source]), 4)
    return out


TASKS: list[Task] = [
    Task("t1", "T1 TCR-epitope binding (NM2025)", BENCH, t1_steps, t1_collect),
    Task("t2", "T2 TCR clustering (TCREmbedding)", BENCH, t2_steps, t2_collect),
    Task("t3", "T3 TCR representation (SCEPTR few-shot)", BENCH, t3_steps, t3_collect),
    Task("t4", "T4 TCR generation (TCRT5)", BENCH, t4_steps, t4_collect),
    Task("mint", "MINT GeneralPPI (5 tasks)", ROOT, mint_steps, mint_collect),
    Task("ab", "Antibody CDR infilling + light pairing", ROOT, ab_steps, ab_collect),
    Task("flab", "FLAb property regression", ROOT, flab_steps, flab_collect),
    Task("nbbench", "NbBench 12-task probing", BENCH, nb_steps, nb_collect),
]
TASK_BY_KEY = {t.key: t for t in TASKS}


def selected(keys: str | None) -> list[Task]:
    if not keys:
        return TASKS
    want = {k.strip() for k in keys.split(",") if k.strip()}
    bad = want - set(TASK_BY_KEY)
    if bad:
        raise SystemExit(f"unknown task keys: {sorted(bad)}; valid: {sorted(TASK_BY_KEY)}")
    return [TASK_BY_KEY[k] for k in TASK_BY_KEY if k in want]


def make_ctx(args) -> Ctx:
    ckpt = Path(args.checkpoint).resolve()
    return Ctx(ckpt=ckpt, run=run_name_of(ckpt), tag=args.tag or default_tag(ckpt))


def cmd_plan(args) -> None:
    c = make_ctx(args)
    print(f"# checkpoint : {c.ckpt}")
    print(f"# run        : {c.run}")
    print(f"# ours spec  : {c.grammar_spec}")
    print(f"# tcr tag    : {c.tag}")
    for task in selected(args.only):
        print(f"\n## [{task.key}] {task.title}   (cwd: {task.cwd})")
        for step in task.steps(c):
            print(f"  {step}")


def cmd_collect(args) -> None:
    c = make_ctx(args)
    summary: dict[str, Any] = {
        "checkpoint": str(c.ckpt), "run": c.run, "tcr_tag": c.tag, "tasks": {}}
    for task in selected(args.only):
        try:
            summary["tasks"][task.key] = {"title": task.title, "metrics": task.collect(c)}
        except Exception as exc:  # noqa: BLE001
            summary["tasks"][task.key] = {"title": task.title, "error": str(exc)}
    if args.out:
        out = Path(args.out)
    elif args.only:
        # Volc launches task families concurrently.  Give partial runs their
        # own output files so their final collectors cannot clobber one another.
        suffix = "_".join(task.key for task in selected(args.only))
        out = GEN / f"summary_{c.run}_{suffix}.json"
    else:
        out = GEN / f"summary_{c.run}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(summary, indent=2))
    print(f"wrote {out}")
    for k, v in summary["tasks"].items():
        m = v.get("metrics") or v.get("error")
        print(f"  {k:8s} {m}")


def cmd_run(args) -> None:
    c = make_ctx(args)
    if not c.ckpt.is_file():
        raise SystemExit(f"checkpoint missing: {c.ckpt}")
    for task in selected(args.only):
        print(f"\n=== [{task.key}] {task.title} ===", flush=True)
        for step in task.steps(c):
            step = step.split("  #")[0].strip()  # drop trailing comment
            print(f"$ (cd {task.cwd}) {step}", flush=True)
            if args.dry_run:
                continue
            rc = subprocess.run(step, shell=True, cwd=str(task.cwd)).returncode
            if rc != 0:
                print(f"[warn] {task.key} step exited rc={rc}", flush=True)
                if not args.keep_going:
                    raise SystemExit(rc)
    cmd_collect(args)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="mode", required=True)
    for name in ("plan", "collect", "run"):
        p = sub.add_parser(name)
        p.add_argument("--checkpoint", required=True, help="abs path to best.pt")
        p.add_argument("--tag", default=None, help="override the ours_globalfeat_* TCR tag")
        p.add_argument("--only", default=None, help="comma list of task keys (t1,t2,t3,t4,mint,ab,flab,nbbench)")
        if name in ("collect", "run"):
            p.add_argument("--out", default=None, help="summary.json path")
        if name == "run":
            p.add_argument("--dry-run", action="store_true")
            p.add_argument("--keep-going", action="store_true")
    args = ap.parse_args()
    {"plan": cmd_plan, "collect": cmd_collect, "run": cmd_run}[args.mode](args)


if __name__ == "__main__":
    main()
